### ISSUE TITLE
überall prüfen ob Spieler gebannt ist

### ISSUE THREAD

**Issue by jonas-merkle** [SoPra-Team-10/GameLogic#118]
In allen Methoden die irgendwas auf dem Env mit Player & Collision & Co. zu tun haben prüfen ob player gebannt sind, da gebannte Spieler nicht auf dem  Spielfeld stehen!
z.B. in cellIsFree & Interceptes

**Comment by jonas-merkle** [comment]
in arbeit in  Feature/BanCheck branch

**Comment by Timmifixedit** [comment]
Kann das weg? @jonas-merkle
