### ISSUE TITLE
shot execute liefert evtl falsche Resultate

### ISSUE THREAD

**Issue by Timmifixedit** [SoPra-Team-10/GameLogic#155]
Manchmal kommt der Quaffle genau auf dem Zielfeld an, aber die shot execute liefert trotzdem kein ThrowSuccess. Vllt macht auch die Streuung Mist. Muss man sich mal genauer anschauen

**Comment by jonas-merkle** [comment]
Ist des noch aktuell?

**Comment by Timmifixedit** [comment]
Bis jetzt nicht mehr aufgetreten
